<?php
/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
 */

namespace Somnambulist\ValueObjects\Types\Geography;

/**
 * Class CountryCodeMappings
 *
 * @package    Somnambulist\ValueObjects\Types\Geography
 * @subpackage Somnambulist\ValueObjects\Types\Geography\CountryCodeMappings
 */
class CountryCodeMappings
{

    /**
     * @param CountryCode $code
     *
     * @return string
     */
    public static function name(CountryCode $code)
    {
        return static::$mappings[$code->value()];
    }

    /**
     * @var array
     */
    private static $mappings = [
        CountryCode::ABW => "Aruba",
        CountryCode::AFG => "Afghanistan",
        CountryCode::AGO => "Angola",
        CountryCode::AIA => "Anguilla",
        CountryCode::ALA => "Åland Islands",
        CountryCode::ALB => "Albania",
        CountryCode::AND => "Andorra",
        CountryCode::ANT => "Netherlands Antilles",
        CountryCode::ARE => "United Arab Emirates",
        CountryCode::ARG => "Argentina",
        CountryCode::ARM => "Armenia",
        CountryCode::ASM => "American Samoa",
        CountryCode::ATA => "Antarctica",
        CountryCode::ATF => "French Southern Territories",
        CountryCode::ATG => "Antigua and Barbuda",
        CountryCode::AUS => "Australia",
        CountryCode::AUT => "Austria",
        CountryCode::AZE => "Azerbaijan",
        CountryCode::BDI => "Burundi",
        CountryCode::BEL => "Belgium",
        CountryCode::BEN => "Benin",
        CountryCode::BES => "Bonaire, Saint Eustatius and Saba",
        CountryCode::BFA => "Burkina Faso",
        CountryCode::BGD => "Bangladesh",
        CountryCode::BGR => "Bulgaria",
        CountryCode::BHR => "Bahrain",
        CountryCode::BHS => "Bahamas",
        CountryCode::BIH => "Bosnia and Herzegovina",
        CountryCode::BLM => "Saint Barthélemy",
        CountryCode::BLR => "Belarus",
        CountryCode::BLZ => "Belize",
        CountryCode::BMU => "Bermuda",
        CountryCode::BOL => "Bolivia",
        CountryCode::BRA => "Brazil",
        CountryCode::BRB => "Barbados",
        CountryCode::BRN => "Brunei Darussalam",
        CountryCode::BTN => "Bhutan",
        CountryCode::BVT => "Bouvet Island",
        CountryCode::BWA => "Botswana",
        CountryCode::CAF => "Central African Republic",
        CountryCode::CAN => "Canada",
        CountryCode::CCK => "Cocos (Keeling) Islands",
        CountryCode::CHE => "Switzerland",
        CountryCode::CHL => "Chile",
        CountryCode::CHN => "China",
        CountryCode::CIV => "Cote D'Ivoire",
        CountryCode::CMR => "Cameroon",
        CountryCode::COD => "Congo, the Democratic Republic of the",
        CountryCode::COG => "Congo",
        CountryCode::COK => "Cook Islands",
        CountryCode::COL => "Colombia",
        CountryCode::COM => "Comoros",
        CountryCode::CPV => "Cape Verde",
        CountryCode::CRI => "Costa Rica",
        CountryCode::CUB => "Cuba",
        CountryCode::CUW => "Curaçao",
        CountryCode::CXR => "Christmas Island",
        CountryCode::CYM => "Cayman Islands",
        CountryCode::CYP => "Cyprus",
        CountryCode::CZE => "Czech Republic",
        CountryCode::DEU => "Germany",
        CountryCode::DJI => "Djibouti",
        CountryCode::DMA => "Dominica",
        CountryCode::DNK => "Denmark",
        CountryCode::DOM => "Dominican Republic",
        CountryCode::DZA => "Algeria",
        CountryCode::ECU => "Ecuador",
        CountryCode::EGY => "Egypt",
        CountryCode::ERI => "Eritrea",
        CountryCode::ESH => "Western Sahara",
        CountryCode::ESP => "Spain",
        CountryCode::EST => "Estonia",
        CountryCode::ETH => "Ethiopia",
        CountryCode::FIN => "Finland",
        CountryCode::FJI => "Fiji",
        CountryCode::FLK => "Falkland Islands (Malvinas)",
        CountryCode::FRA => "France",
        CountryCode::FRO => "Faroe Islands",
        CountryCode::FSM => "Micronesia, Federated States of",
        CountryCode::GAB => "Gabon",
        CountryCode::GBR => "United Kingdom",
        CountryCode::GEO => "Georgia",
        CountryCode::GGY => "Guernsey",
        CountryCode::GHA => "Ghana",
        CountryCode::GIB => "Gibraltar",
        CountryCode::GIN => "Guinea",
        CountryCode::GLP => "Guadeloupe",
        CountryCode::GMB => "Gambia",
        CountryCode::GNB => "Guinea-Bissau",
        CountryCode::GNQ => "Equatorial Guinea",
        CountryCode::GRC => "Greece",
        CountryCode::GRD => "Grenada",
        CountryCode::GRL => "Greenland",
        CountryCode::GTM => "Guatemala",
        CountryCode::GUF => "French Guiana",
        CountryCode::GUM => "Guam",
        CountryCode::GUY => "Guyana",
        CountryCode::HKG => "Hong Kong",
        CountryCode::HMD => "Heard Island and Mcdonald Islands",
        CountryCode::HND => "Honduras",
        CountryCode::HRV => "Croatia",
        CountryCode::HTI => "Haiti",
        CountryCode::HUN => "Hungary",
        CountryCode::IDN => "Indonesia",
        CountryCode::IMN => "Isle of Man",
        CountryCode::IND => "India",
        CountryCode::IOT => "British Indian Ocean Territory",
        CountryCode::IRL => "Ireland",
        CountryCode::IRN => "Iran, Islamic Republic of",
        CountryCode::IRQ => "Iraq",
        CountryCode::ISL => "Iceland",
        CountryCode::ISR => "Israel",
        CountryCode::ITA => "Italy",
        CountryCode::JAM => "Jamaica",
        CountryCode::JEY => "Jersey",
        CountryCode::JOR => "Jordan",
        CountryCode::JPN => "Japan",
        CountryCode::KAZ => "Kazakhstan",
        CountryCode::KEN => "Kenya",
        CountryCode::KGZ => "Kyrgyzstan",
        CountryCode::KHM => "Cambodia",
        CountryCode::KIR => "Kiribati",
        CountryCode::KNA => "Saint Kitts and Nevis",
        CountryCode::KOR => "Korea, Republic of",
        CountryCode::KWT => "Kuwait",
        CountryCode::LAO => "Lao People's Democratic Republic",
        CountryCode::LBN => "Lebanon",
        CountryCode::LBR => "Liberia",
        CountryCode::LBY => "Libyan Arab Jamahiriya",
        CountryCode::LCA => "Saint Lucia",
        CountryCode::LIE => "Liechtenstein",
        CountryCode::LKA => "Sri Lanka",
        CountryCode::LSO => "Lesotho",
        CountryCode::LTU => "Lithuania",
        CountryCode::LUX => "Luxembourg",
        CountryCode::LVA => "Latvia",
        CountryCode::MAC => "Macao",
        CountryCode::MAF => "Saint Martin (French part)",
        CountryCode::MAR => "Morocco",
        CountryCode::MCO => "Monaco",
        CountryCode::MDA => "Moldova, Republic of",
        CountryCode::MDG => "Madagascar",
        CountryCode::MDV => "Maldives",
        CountryCode::MEX => "Mexico",
        CountryCode::MHL => "Marshall Islands",
        CountryCode::MKD => "Macedonia, the Former Yugoslav Republic of",
        CountryCode::MLI => "Mali",
        CountryCode::MLT => "Malta",
        CountryCode::MMR => "Myanmar",
        CountryCode::MNE => "Montenegro",
        CountryCode::MNG => "Mongolia",
        CountryCode::MNP => "Northern Mariana Islands",
        CountryCode::MOZ => "Mozambique",
        CountryCode::MRT => "Mauritania",
        CountryCode::MSR => "Montserrat",
        CountryCode::MTQ => "Martinique",
        CountryCode::MUS => "Mauritius",
        CountryCode::MWI => "Malawi",
        CountryCode::MYS => "Malaysia",
        CountryCode::MYT => "Mayotte",
        CountryCode::NAM => "Namibia",
        CountryCode::NCL => "New Caledonia",
        CountryCode::NER => "Niger",
        CountryCode::NFK => "Norfolk Island",
        CountryCode::NGA => "Nigeria",
        CountryCode::NIC => "Nicaragua",
        CountryCode::NIU => "Niue",
        CountryCode::NLD => "Netherlands",
        CountryCode::NOR => "Norway",
        CountryCode::NPL => "Nepal",
        CountryCode::NRU => "Nauru",
        CountryCode::NZL => "New Zealand",
        CountryCode::OMN => "Oman",
        CountryCode::PAK => "Pakistan",
        CountryCode::PAN => "Panama",
        CountryCode::PCN => "Pitcairn",
        CountryCode::PER => "Peru",
        CountryCode::PHL => "Philippines",
        CountryCode::PLW => "Palau",
        CountryCode::PNG => "Papua New Guinea",
        CountryCode::POL => "Poland",
        CountryCode::PRI => "Puerto Rico",
        CountryCode::PRK => "Korea, Democratic People's Republic of",
        CountryCode::PRT => "Portugal",
        CountryCode::PRY => "Paraguay",
        CountryCode::PSE => "Palestinian Territory, Occupied",
        CountryCode::PYF => "French Polynesia",
        CountryCode::QAT => "Qatar",
        CountryCode::REU => "Reunion",
        CountryCode::ROM => "Romania",
        CountryCode::RUS => "Russian Federation",
        CountryCode::RWA => "Rwanda",
        CountryCode::SAU => "Saudi Arabia",
        CountryCode::SCG => "Serbia and Montenegro",
        CountryCode::SDN => "Sudan",
        CountryCode::SEN => "Senegal",
        CountryCode::SGP => "Singapore",
        CountryCode::SGS => "South Georgia and the South Sandwich Islands",
        CountryCode::SHN => "Saint Helena",
        CountryCode::SJM => "Svalbard and Jan Mayen",
        CountryCode::SLB => "Solomon Islands",
        CountryCode::SLE => "Sierra Leone",
        CountryCode::SLV => "El Salvador",
        CountryCode::SMR => "San Marino",
        CountryCode::SOM => "Somalia",
        CountryCode::SPM => "Saint Pierre and Miquelon",
        CountryCode::SRB => "Serbia",
        CountryCode::STP => "Sao Tome and Principe",
        CountryCode::SUR => "Suriname",
        CountryCode::SVK => "Slovakia",
        CountryCode::SVN => "Slovenia",
        CountryCode::SWE => "Sweden",
        CountryCode::SWZ => "Swaziland",
        CountryCode::SXM => "Sint Maarten (Dutch part)",
        CountryCode::SYC => "Seychelles",
        CountryCode::SYR => "Syrian Arab Republic",
        CountryCode::TCA => "Turks and Caicos Islands",
        CountryCode::TCD => "Chad",
        CountryCode::TGO => "Togo",
        CountryCode::THA => "Thailand",
        CountryCode::TJK => "Tajikistan",
        CountryCode::TKL => "Tokelau",
        CountryCode::TKM => "Turkmenistan",
        CountryCode::TLS => "Timor-Leste",
        CountryCode::TON => "Tonga",
        CountryCode::TTO => "Trinidad and Tobago",
        CountryCode::TUN => "Tunisia",
        CountryCode::TUR => "Turkey",
        CountryCode::TUV => "Tuvalu",
        CountryCode::TWN => "Taiwan, Province of China",
        CountryCode::TZA => "Tanzania, United Republic of",
        CountryCode::UGA => "Uganda",
        CountryCode::UKR => "Ukraine",
        CountryCode::UMI => "United States Minor Outlying Islands",
        CountryCode::URY => "Uruguay",
        CountryCode::USA => "United States of America",
        CountryCode::UZB => "Uzbekistan",
        CountryCode::VAT => "Holy See (Vatican City State)",
        CountryCode::VCT => "Saint Vincent and the Grenadines",
        CountryCode::VEN => "Venezuela",
        CountryCode::VGB => "Virgin Islands, British",
        CountryCode::VIR => "Virgin Islands, U.s.",
        CountryCode::VNM => "Viet Nam",
        CountryCode::VUT => "Vanuatu",
        CountryCode::WLF => "Wallis and Futuna",
        CountryCode::WSM => "Samoa",
        CountryCode::YEM => "Yemen",
        CountryCode::ZAF => "South Africa",
        CountryCode::ZMB => "Zambia",
        CountryCode::ZWE => "Zimbabwe",
    ];
}
